name: Example CICD Workflow with Node.js

# Trigger kalau ada push ke branch main atau develop
on:
  push:
    branches: [main, develop]

# Pekerjaan yang akan dijalankan
jobs:
  ci_test:
    runs-on: ubuntu-latest # menggunakan sistem operasi Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'

    # - name: Install dependencies
    #   run: npm install
    #   working-directory: ./02_Node_Example

    # - name: Run tests
    #   run: npm test
    #   working-directory: ./02_Node_Example